name: hello-world
on: push
jobs:
  my-job:
    runs-on: special-k
    env:
      GITHUB_TOKEN: ${{ github.token }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v4
      - name: my-step
        run: echo "Hello, World!"
      - name: print envs
        run: |
          echo "pre-job envs"
          cat /home/runner/pre-job-envs.txt
          echo "---------------------------------------"
          echo "id-jwt"
          # cat /home/runner/id-jwt.json
          echo "---------------------------------------"
          echo "pre-job-event-details"
          cat /home/runner/pre-job-event-details.txt
          echo "---------------------------------------"
          echo "Local Envs"
          env | sort
      - name: build docker
        run: |
          docker build . -t testcontainer
          docker run --rm -t testcontainer cat testfile
      - name: my-step2
        run:  |
          for i in {1..10}; do
            echo "${i} - Good Bye, Cruel World!"
            sleep 1
          done
      - name: run container step
        uses: docker://ubuntu:18.04
        with:
          args: |
            echo "Hello World"
            echo "Goodbye Cruel World"
