name: hello-world
on: push
jobs:
  my-job:
    runs-on: special-k
    steps:
      - name: my-step
        run: echo "Hello, World!"
      - name: my-step2
        run:  |
          for i in {1..100}; do
            echo "Hello, Cruel World ${i}!"
            sleep 1
          done