name: hello-world
on: push
jobs:
  my-job:
    runs-on: special-k
    container:
      image: ubuntu:22.04
    env:
      GITHUB_TOKEN: ${{ github.token }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: my-step
        run: |
          echo "Hello, World!" | tee helloworld.txt
      - name: print envs
        run: |
          cat helloworld.txt
          echo "pre-job envs"
          cat /home/runner/pre-job-envs.txt
          echo "---------------------------------------"
          echo "id-jwt"
          # cat /home/runner/id-jwt.json
          echo "---------------------------------------"
          echo "pre-job-event-details"
          cat /home/runner/pre-job-event-details.txt
          echo "---------------------------------------"
          echo "Local Envs"
          env | sort
      - name: my-step2
        run:  |
          for i in {1..30}; do
            echo "${i} - Good Bye, Cruel World!"
            sleep 1
          done