name: hello-world
on: push
jobs:
  my-job:
    runs-on: special-k
    steps:
      - name: my-step
        run: echo "Hello, World!"
      - name: print envs
        run: |
          echo "pre-job envs"
          cat /home/runner/pre-job-envs.txt
          echo "---------------------------------------"
          echo "pre-job-event-details"
          cat /home/runner/pre-job-event-details.txt
          echo "---------------------------------------"
          echo "Local Envs"
          env | sort
      - name: my-step2
        run:  |
          for i in {1..100}; do
            echo "Hello, Cruel World ${i}!"
            sleep 1
          done